### ISSUE TITLE
Add dynamic return type extension for enums

### ISSUE THREAD

**Issue by adaamz** [marc-mabe/php-enum-phpstan#1]
Hi,
in general there should be create dynamic return type extension. It will allow us to exactly know returned value from function call, or at least returned type.

Take example from
https://github.com/adaamz/phpstan-mabe-enum/blob/045e4ad/src/DynamicReturnTypeExtension.php
I'm not sure if it is up-to-date with latest phpstan, must check :)

**Comment by marc-mabe** [comment]
Hi @adaamz,

This would be a great extension.
Currently I have very limited time ... do you like to open a PR?
