### ISSUE TITLE
PHPStan 2.0

### ISSUE THREAD

**Issue by nloyola** [marc-mabe/php-enum-phpstan#14]
I'm using PHPStan 2.0 and get `Call to an undefined static method` errors.

Does this package work with PHPStan 2.0?

**Comment by marc-mabe** [comment]
Please can you point me to PHPStan 2.0

**Comment by nloyola** [comment]
Oh no! Sorry for the trouble. I misread my composer.json.

I'm actually using PHPStan 1.5.
