### ISSUE TITLE
PHPStan 1.5.4

### ISSUE THREAD

**Issue by nloyola** [marc-mabe/php-enum-phpstan#15]
I'm using [PHPStan 1.5.4](https://github.com/phpstan/phpstan/releases/tag/1.5.4) and get `Call to an undefined static method` errors.

I've modified my `phpstan.neon` file as stated in the installation instructions but still get errors.

**Comment by marc-mabe** [comment]
@nloyola Please add more information as I can't reproduce your issue with PHPStan 1.5.4.

* PHP Version
* Config
* Output of `phpstan -vvv --debug`

**Comment by nloyola** [comment]
I'm using:

* PHP Version: 7.4.28
* Config: I created a GitHub Project at https://github.com/nloyola/php-enum-phpstan-test

### PHPStan output

```
> vendor/bin/phpstan analyse -vvv --debug --no-ansi -c phpstan.neon --error-format=raw

Result cache not used because of debug mode.
/home/nelson/tmp/php-enum-phpstan-test/src/PhpEnumPhpStanTest.php
1
2
--- consumed 8 MB, total 66 MB, took 0.06 s
Result cache is saved.
/home/nelson/tmp/php-enum-phpstan-test/src/PhpEnumPhpStanTest.php:13:Constant PhpEnumPhpStanTest\TestEnum::ONE is unused.
/home/nelson/tmp/php-enum-phpstan-test/src/PhpEnumPhpStanTest.php:14:Constant PhpEnumPhpStanTest\TestEnum::TWO is unused.
/home/nelson/tmp/php-enum-phpstan-test/src/PhpEnumPhpStanTest.php:19:Call to an undefined static method PhpEnumPhpStanTest\TestEnum::ONE().
/home/nelson/tmp/php-enum-phpstan-test/src/PhpEnumPhpStanTest.php:20:Call to an undefined static method PhpEnumPhpStanTest\TestEnum::TWO().
Used memory: 66 MB
```

**Comment by marc-mabe** [comment]
You are using `use MyCLabs\Enum\Enum;` but this PHPStan extension is for https://github.com/marc-mabe/php-enum

PS: If you start a new project and don't plan to use `EnumSet` or `EnumMap` I would recommend https://github.com/marc-mabe/php-enum-cl which is forward compatible to native enums added in PHP 8.1

**Comment by nloyola** [comment]
OMG. Apologies once again. I got confused by the common name `php-enum`.
